import React from 'react'
import blogImg1 from '../assets/images/1-Figure1-1.png' 
import blogImg2 from '../assets/images/ecdc4f6258e9248574024d97dba2fd4e.jpg' 
import blogImg3 from '../assets/images/resource ef-1300x731.jpg' 
import blogImg4 from '../assets/images/4880741.jpg' 
import blogImg5 from '../assets/images/img-05.jpg' 
import {Link} from 'react-router-dom'
import '../styles/instruction.css'
import { Container, Row, Col } from 'reactstrap'
import img from '../assets/images/instruction (1).png'
import Subtitle from '../shared/Subtitle'

const Instruction = () => {

  const posts = [
    {
      id:1,
      title:"How To Duel With Waste?",
      desc:"Industrial garbage is the waste generated by various industrial activities, such as manufacturing, processing, mining, etc. Industrial garbage can be solid, liquid, or gaseous, and can have different characteristics and impacts depending on the type of industry and waste. Industrial garbage disposal requires specialized methods that can handle the volume, composition, and hazards of the waste. Some of the common methods are landfill, incineration, composting, recycling, and waste-to-energy. Some examples of how to handle industrial garbage are: Landfill: Burying solid waste in a designated area that is properly designed and managed to prevent environmental problems such as leachate, methane gas, odors.",
      img: blogImg1,
    },
    {
      id:2,
      title:"The Power of the 3Rs: Mastering Reduce, Reuse, and Recycle",
      desc:"One of the most effective ways to protect the environment and conserve natural resources is to follow the 3R principle: Reduce, Reuse, and Recycle. These three actions can help us minimize the amount of waste we generate, save energy and money, and prevent pollution and climate change. Let’s see how we can apply the 3R in our daily lives. Reducing means using less of something or avoiding unnecessary consumption. By reducing the amount of waste we produce, we can save natural resources, landfill space, and energy. Some examples of reducing are: Buying products with less packaging or in bulk. Using reusable bags, bottles, and containers. Avoiding single-use items, such as disposable cups, plates, cutlery, and straws. Choosing durable and long-lasting products that do not need frequent replacement. Borrowing, renting, or sharing items that are not used often. Turning off lights and appliances when not in use. Taking shorter showers and fixing leaky faucets ",
      img: blogImg2,
    },
    {
      id:3,
      title:"How Can We Use Resources More Efficiently?",
      desc:"Using efficient resources like electricity and water is not only good for the environment, but also for your wallet. By saving energy and water, you can reduce your utility bills, greenhouse gas emissions, and water footprint. Here are some tips on how to use efficient resources like electricity and water: Sure, here’s my suggestion for editing the content: Choose Energy-Efficient Appliances: Opt for appliances, electronics, equipment, and lighting that have the Energy Star label or similar certification. These products consume less energy compared to standard ones. For example, an Energy Star refrigerator uses about 20% less energy than a non-certified one, potentially saving up to 30% of energy overall. Mind Your Devices: Turn off or unplug devices that aren’t in use or employ a power strip to cut off standby power. Many devices still draw electricity even when turned off. A laptop, for instance, consumes around 15 watts when plugged in but not active, so by being mindful, you can save up to 10% of energy and reduce your carbon footprint by 1,000 pounds annually.",
      img: blogImg3,
    },
    {
      id:4,
      title:"Embarking on a Green Journey: Steps to an Eco-Friendly Lifestyle",
      desc:"Welcome to your guide to sustainable living. Our planet is at a crossroads, and each of us has a role to play. Whether you're new to eco-friendly practices or seeking to enhance your green journey, this page offers practical steps for meaningful change. Every choice we make can ripple toward a greener tomorrow. Dive in to discover how you can make a difference today. How to Live a Green Lifestyle? Choose public transport, walking, or biking over driving. If driving is necessary, opt for fuel-efficient or electric vehicles. Make use of carpooling or car-sharing services to minimize individual car usage. Minimize air travel and consider compensating for the carbon footprint when you do.",
      img: blogImg4,
    },
    {
      id:5,
      title:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lobortis purus sapien, nec pellentesque quam vehicula ac",
      desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lobortis purus sapien, nec pellentesque quam vehicula ac. Duis euismod, mi vitae dapibus tincidunt, orci dui malesuada dolor, in sollicitudin lorem mauris vel est. Praesent egestas convallis cursus. Curabitur nec urna leo. Donec interdum nulla justo, eget tempus lorem venenatis a. Phasellus lectus diam, laoreet interdum consequat ut, mollis placerat metus.",
      img: blogImg5,
    },
  ]
  return (
    <>
      <section className='instruction__intro'>
        <Container>
            <Row>
                <Col lg='6' >
                  <div className='instruction__img'>
                    <img src={img} alt='' />
                  </div>
                </Col>

                <Col lg='6'>
                    <div className='instruction__content'>
                        <Subtitle subtitle={'Our instruction'}  />

                        <p className='instruction__description mt-4'>
                        A beacon for responsible environmental actions. In our pursuit to foster a healthier planet, we understand that every positive step counts. This page is designed to provide you with clear, actionable instructions on managing and minimizing waste, understanding the 3Rs (Reduce, Reuse, Recycle), optimizing resource usage, and embracing a greener lifestyle. 
                        <br />
                        <br />
                        Whether you're a novice seeking basic guidelines or someone deeply embedded in the cause, our comprehensive instructions serve as a roadmap to make an impactful difference. 
                        <span> Let's come together and sow the seeds for a brighter, more sustainable future!</span>
                        </p>
                    </div>
                    
                </Col>
            </Row>
        </Container>
    </section>



      <section className='instruction__wrapper'>
      <Container>
          <div className='instruction'>
          {posts.map(post=> (
            <div className='instruction__post' key={post.id}>
              <div className='img'>
                <img src={post.img} alt='' />
              </div>
              
              <div className='content'>
                <Link className='link' to={`/instruction/${post.id}`}>
                  <h1>{post.title}</h1>
                </Link>
                <p>{post.desc}</p>
                <button className='btn primary__btn'>Read More</button>
              </div>
            </div>
          ))}
        </div>
      </Container>
    </section>
    </>
   
    
  )
}

export default Instruction